name: football_matches
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.0.0
  hydrated_bloc: ^9.0.0
  go_router: ^14.6.1
  equatable: ^2.0.5
  get_it: ^8.0.2
  flutter_screenutil: ^5.8.4
  google_fonts: ^6.0.0
  lottie: ^3.1.3
  animated_text_kit: ^4.2.2
  flutter_svg: ^2.0.16
  vector_graphics: ^1.1.15
  persistent_bottom_nav_bar: ^6.2.1
  fl_chart: ^0.69.2
  flutter_dash: ^1.0.0
  mobkit_dashed_border: ^0.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen_runner: ^5.4.0
  flutter_svg_opt: ^0.0.1
  flutter_lints: ^5.0.0
  build_runner: ^2.4.0
  flutter_launcher_icons: ^0.14.1
  lint: ^2.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/json/

flutter_gen:
  integrations:
    flutter_svg: true